version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://serena_user:serena_password@postgres:5432/serena_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - VERIFY_TOKEN=${VERIFY_TOKEN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ../backend:/app
    networks:
      - serena-network
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=serena_user
      - POSTGRES_PASSWORD=serena_password
      - POSTGRES_DB=serena_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - serena-network

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - serena-network

networks:
  serena-network:
    driver: bridge

volumes:
  postgres-data: